import Head from 'next/head'
import prisma from './../lib/prisma'
import { getJobs } from './../lib/jobs'
import Jobs from '/components/jobs'
import Link from 'next/link'
import { useSession, signOut } from 'next-auth/react'

export default function Home({ jobs }) {
  const { data: session, status } = useSession()
  console.log(session)
  return (
    <>
      <Head>
        <title>Job-Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex w-full h-[3rem] bg-gray-200'>
        {!session ? (



          <Link href='/api/auth/signin'>
            <div className='flex justify-end py-2'>
              <div className='w-[70px] h-[2rem] flex'>
                <button className='rounded-full bg-gray-400 hover:bg-gray-600 text-white font-bold w-full'>
                  Login
                </button>

              </div>

            </div>

          </Link>



        ) : <div className='flex justify-end py-2'>
          <div className='w-full h-[2rem] flex'>
            <button onClick={signOut} className='rounded-full bg-gray-400 hover:bg-gray-600 text-white font-bold w-full'>
              Logout {session.name}
            </button>

          </div>

        </div>}
      </div>

      <div className='mt-10'>
        <div className='text-center p-4 m-4'>
          <h2 className='mb-10 text-4xl font-bold'>Find a job!</h2>
        </div>
        <Jobs jobs={jobs} />
      </div>

    </>
  )
}



export async function getServerSideProps(context) {
  let jobs = await getJobs(prisma)
  jobs = JSON.parse(JSON.stringify(jobs))

  return {
    props: {
      jobs,
    },
  }
}