import Head from 'next/head'
import prisma from './../lib/prisma'
import { getJobs } from './../lib/jobs'
import Jobs from '/components/jobs'

export default function Home({jobs}) {

  return (
    <>
      <Head>
        <title>Job-Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className='mt-10'>
      <div className='text-center p-4 m-4'>
        <h2 className='mb-10 text-4xl font-bold'>Find a job!</h2>
      </div>
      <Jobs jobs={jobs} />
    </div>

    </>
  )
}



export async function getServerSideProps(context) {
  let jobs = await getJobs(prisma)
	jobs = JSON.parse(JSON.stringify(jobs))

  return {
    props: {
      jobs,
    },
  }
}